version: "2"
linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - ginkgolinter
    - musttag
    - nlreturn
    - tagalign
    - varnamelen
    - gochecknoinits
    - gochecknoglobals
    - wrapcheck
    - wsl
    - godox
    - protogetter
    - lll
    - revive
  settings:

  exclusions:
    rules:
      - path: "_test.go"
        linters:
          - funlen
          - maintidx
          - goconst
          - dupl
      - path: "service/error.go"
        linters:
          - ireturn
formatters:
  enable:
    - gci
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/NamanBalaji/tdm)
        - blank
        - dot
        - alias
        - localmodule