version: "2"

run:
  tests: false

linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - ginkgolinter
    - musttag
    - nlreturn
    - tagalign
    - varnamelen
    - gochecknoinits
    - gochecknoglobals
    - wrapcheck
    - wsl
    - godox
    - protogetter
    - lll
    - revive
    - noinlineerr
    - ireturn
    - interfacebloat
    - gosec
    - forcetypeassert
    - gocritic
    - mnd
    - noctx
  settings:
    cyclop:
      max-complexity: 25
    gocognit:
      min-complexity: 40
    funlen:
      lines: 85
      statements: 60

formatters:
  enable:
    - gci
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/NamanBalaji/tdm)
        - blank
        - dot
        - alias
        - localmodule
