name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g. v1.2.3)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, darwin, windows]
        arch: [amd64]
    name: Build ${{ matrix.os }} / ${{ matrix.arch }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.x'
          cache: true

      - name: Compute output filename
        run: |
          if [ "${{ matrix.os }}" = "windows" ]; then
            echo "OUTPUT=tdm-windows-${{ matrix.arch }}.exe" >> $GITHUB_ENV
          else
            echo "OUTPUT=tdm-${{ matrix.os }}-${{ matrix.arch }}" >> $GITHUB_ENV
          fi

      - name: Build binary
        run: |
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} \
            go build -o "${{ env.OUTPUT }}" ./cmd

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-artifact
          path: ${{ env.OUTPUT }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: '*-artifact'
          merge-multiple: true
          path: artifacts

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name:    ${{ github.event.inputs.version }}
          release_name: Release ${{ github.event.inputs.version }}
          draft:        false
          prerelease:   false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Linux asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url:        ${{ steps.create_release.outputs.upload_url }}
          asset_path:        artifacts/linux-artifact/tdm-linux-amd64
          asset_name:        tdm-linux-amd64
          asset_content_type: application/octet-stream

      - name: Upload macOS asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url:        ${{ steps.create_release.outputs.upload_url }}
          asset_path:        artifacts/darwin-artifact/tdm-darwin-amd64
          asset_name:        tdm-darwin-amd64
          asset_content_type: application/octet-stream

      - name: Upload Windows asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url:        ${{ steps.create_release.outputs.upload_url }}
          asset_path:        artifacts/windows-artifact/tdm-windows-amd64.exe
          asset_name:        tdm-windows-amd64.exe
          asset_content_type: application/octet-stream
