name: Manual Release

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g. v1.2.3)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        include:
          - os: linux
            arch: amd64
            ext: ""
          - os: darwin
            arch: amd64
            ext: ""       # Intel Macs
          - os: darwin
            arch: arm64
            ext: ""       # Apple Silicon :contentReference[oaicite:2]{index=2}
          - os: windows
            arch: amd64
            ext: ".exe"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.x'
          cache: true

      - name: Compute output filename
        run: |
          echo "OUTPUT=tdm${{ matrix.ext }}" >> $GITHUB_ENV

      - name: Build binary
        run: |
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} \
            go build -o "${{ env.OUTPUT }}" ./cmd

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}-artifact
          path: ${{ env.OUTPUT }}

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: '*-artifact'
          merge-multiple: true
          path: artifacts

      - name: List downloaded files
        run: ls -R artifacts

      - name: Create or update GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag:           ${{ github.event.inputs.version }}
          name:          Release ${{ github.event.inputs.version }}
          artifacts: |
            artifacts/linux-amd64-artifact/tdm
            artifacts/darwin-amd64-artifact/tdm
            artifacts/darwin-arm64-artifact/tdm
            artifacts/windows-amd64-artifact/tdm.exe
          allowUpdates:  true
          draft:         false
          prerelease:    false
        env:
          GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}